version: "3"

networks:
  docker-net:
    name: docker-net
    external: true

services:
  phpmailer:
    image: php:8.2-apache
    ports:
      - "80:80"
    networks:
      - docker-net
    volumes:
      - ./smtp:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf

  mailhog:
    image: mailhog/mailhog:latest
    networks:
      - docker-net
    ports:
      - "8025:8025"
